### ISSUE TITLE
Firefox

### ISSUE THREAD

**Issue by tizmagik** [kristoferbaxter/preset-env-modules#1]
Hey @kristoferbaxter unfortunately this doesn't seem to work for Firefox :(

**Comment by kristoferbaxter** [comment]
Strange! I just tried this using Firefox – Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:58.0) Gecko/20100101 Firefox/58.0 and it appears to be working.

![screen shot 2018-02-01 at 11 55 41 am](https://user-images.githubusercontent.com/61764/35700179-1742d192-0747-11e8-81c2-ed20d2826cb9.png)

Could you provide more details? OS, Version, etc?

**Comment by tizmagik** [comment]
Oh sorry @kristoferbaxter I should have added some more detail, I mean doesn't work in the sense that both scripts are loaded (although the modules one doesn't get parsed/executed which is good), but unfortunately this would mean shipping 2x the bundle to Firefox essentially :(

![image](https://user-images.githubusercontent.com/244704/35701889-6946b65c-0765-11e8-8ce7-368a1fb07e09.png)

**Comment by kristoferbaxter** [comment]
I see, yes FF is transferring both files. Will take a look.

**Comment by kristoferbaxter** [comment]
Files an issue on Bugzilla (https://bugzilla.mozilla.org/show_bug.cgi?id=1435439).

Looking for a workaround.

**Comment by tizmagik** [comment]
Thanks for the bug report!

**Comment by kristoferbaxter** [comment]
Update: Issue is partially fixed in Firefox 60.

**Comment by kristoferbaxter** [comment]
Addressed as of Firefox 61. Issue on Bugzilla was marked as `WONT FIX`.
